version: "3.6"

services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    networks:
      pihole_net:
        ipv4_address: 10.0.0.2

  pihole:
    container_name: pihole
    image: pihole/pihole
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: "America/Los_Angeles"
      DNS1: 10.0.0.2#5054
      DNS2: "" #'1.1.1.1'
      DNSMASQ_LISTENING: all
    networks:
      pihole_net:
        ipv4_address: 10.0.0.3
    volumes:
      - "/mnt/app-data/pihole/config:/etc/pihole/"
      - "/mnt/app-data/pihole/dnsmasq:/etc/dnsmasq.d/"
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    depends_on:
      - cloudflared

networks:
  pihole_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/29
