version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: "${TIMEZONE}"
      WEBPASSWORD: "${PASSWORD}"
    volumes:
      - "/mnt/app-data/pihole/config:/etc/pihole/"
      - "/mnt/app-data/pihole/dnsmasq:/etc/dnsmasq.d/"
    restart: unless-stopped
